### ISSUE TITLE
падение после неудачного удаления приложения

### ISSUE THREAD

**Issue by andrew-olegovi4** [saursvepur/vepurovk#1]
при попытке удаления приложения сеть полностью упала: 
https://disk.yandex.ru/i/9vXF9iPgbKHDTQ
https://disk.yandex.ru/i/vvRYZmy9fzPoBw

**Comment by saursvepur** [comment]
Сейчас проблема не из-за удаления приложения а на стороне хостинга xd

**Comment by saursvepur** [comment]
@andrew-olegovi4 ахах ору, вот так совпадение

**Comment by andrew-olegovi4** [comment]
@saursvepur я как раз нашёл реп и инфу про нестабильность)

**Comment by andrew-olegovi4** [comment]
и код я вообще не смотрел, подумал, что всё плачевно, аххахпх

**Comment by andrew-olegovi4** [comment]
@saursvepur рад, что совпадение)
